# Generated by Django 3.2.16 on 2022-10-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbstractModelForCatalog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="", max_length=150)),
                ("is_published", models.BooleanField(default=True)),
            ],
        ),
    ]
