# Generated by Django 3.2.16 on 2022-10-31 10:23

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogCategory",
            fields=[
                (
                    "abstractmodelforcatalog_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.abstractmodelforcatalog",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        default="",
                        max_length=200,
                        unique=True,
                        validators=[catalog.validators.only_chars_validator],
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        default=100,
                        validators=[catalog.validators.num_compare_validator],
                    ),
                ),
            ],
            bases=("core.abstractmodelforcatalog",),
        ),
        migrations.CreateModel(
            name="CatalogItem",
            fields=[
                (
                    "abstractmodelforcatalog_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.abstractmodelforcatalog",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        default="",
                        validators=[catalog.validators.in_value_validator]
                    ),
                ),
            ],
            bases=("core.abstractmodelforcatalog",),
        ),
        migrations.CreateModel(
            name="CatalogTag",
            fields=[
                (
                    "abstractmodelforcatalog_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.abstractmodelforcatalog",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        default="",
                        max_length=200,
                        unique=True,
                        validators=[catalog.validators.only_chars_validator],
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.catalogitem",
                    ),
                ),
            ],
            bases=("core.abstractmodelforcatalog",),
        ),
    ]
