# Generated by Django 3.2.16 on 2022-11-01 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_auto_20221101_1220"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.catalogcategory",
                verbose_name="Категория",
            ),
        ),
    ]
