# Generated by Django 3.2.16 on 2022-11-08 17:47

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20221102_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='upload',
            field=models.ImageField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='text',
            field=models.TextField(default='', validators=[catalog.validators.in_value_validator], verbose_name='Текст'),
        ),
    ]
