# Generated by Django 3.2.16 on 2022-11-08 18:28

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20221108_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='text',
            field=models.TextField(default='', validators=[catalog.validators.in_value_validator], verbose_name='Текст'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.catalogitem')),
            ],
        ),
    ]
