# Generated by Django 3.2.16 on 2022-11-10 18:27

from django.db import migrations, models

import catalog.validators


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_catalogitem_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={"verbose_name": "Превью", "verbose_name_plural": "Превью"},
        ),
        migrations.AddField(
            model_name="photo",
            name="name",
            field=models.CharField(default="", max_length=150, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="catalogitem",
            name="text",
            field=models.TextField(
                default="",
                validators=[catalog.validators.in_value_validator],
                verbose_name="Текст",
            ),
        ),
    ]
