# Generated by Django 3.2.16 on 2022-11-14 17:13

from django.db import migrations, models

import catalog.validators


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_auto_20221110_2155"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogitem",
            name="is_on_main",
            field=models.BooleanField(default=False, verbose_name="Is_on_main"),
        ),
        migrations.AlterField(
            model_name="catalogitem",
            name="text",
            field=models.TextField(
                default="",
                validators=[catalog.validators.in_value_validator],
                verbose_name="Текст",
            ),
        ),
    ]
