# Generated by Django 3.2.16 on 2022-11-18 16:49

from django.db import migrations, models

import catalog.validators


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_auto_20221114_2013"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogitem",
            name="text",
            field=models.TextField(
                default="",
                validators=[catalog.validators.in_value_validator],
                verbose_name="Текст",
            ),
        ),
    ]
