# Generated by Django 3.2.16 on 2022-11-18 17:04

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_catalogitem_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='text',
            field=models.TextField(default='', validators=[catalog.validators.in_value_validator], verbose_name='Текст'),
        ),
    ]
